/**
 * HELP KNOWLEDGE BASE (V36) — the repo-grounded RAG behind "HELP ME NOW". A curated, DOM-free corpus
 * of project knowledge (one card per topic, distilled from README/Docs/Specs/ENTITY-SHEETS) + a small
 * keyword retriever, so the help panel answers "Explain this / What is that? / I'm confused" instantly
 * and OFFLINE — no dependency on the external AI (which can be rate-limited). The ✦ Copilot still
 * handles freeform + web questions; this is the always-available, grounded first line.
 *
 * Safety constitution (baked in): every card here is PUBLIC project knowledge — architecture, science,
 * how-to-play. Nothing here is a secret, a credential, private data, or a sensitive matter, so a
 * grounded answer can never leak one. Pure + deterministic; unit-tested via {@link findHelp}.
 */

export interface HelpEntry {
  id: string;
  title: string;
  /** Extra match terms beyond the title/body words (synonyms, entity names). */
  keywords: string[];
  /** The grounded answer — plain text, a few sentences. */
  body: string;
  /** Where to read more (doc paths / panels). */
  see?: string[];
}

/** The corpus. Kept concise + accurate to the codebase; grows as the world does. */
export const HELP_KB: readonly HelpEntry[] = [
  {
    id: 'overview',
    title: 'What is this?',
    keywords: [
      'overview',
      'what is this',
      'explain this',
      'confused',
      'start',
      'cosmogonic',
      'sim',
      'game',
      'about',
    ],
    body: 'The Cosmogonic Quantum Mechalogodrom is a living chaos-biome simulation: thousands of procedural creatures drift, feed, mutate and trade inside a reactive cosmos, watched over by apex minds. Every visual effect sits on real math, and every system both reads and writes another — cognition feeds the economy, the economy steers war, war triggers sanctions. Open the panels from the menu bar (centered, just above the bottom toolbar) to inspect any layer live.',
    see: ['docs/PHILOSOPHY-2026-06-26.md', 'README.md'],
  },
  {
    id: 'how-to-play',
    title: 'How do I play / what do the controls do?',
    keywords: [
      'controls',
      'how to play',
      'keys',
      'buttons',
      'mouse',
      'camera',
      'navigate',
      'confused',
      'lost',
    ],
    body: 'Drag to orbit the camera, scroll to zoom. The bottom toolbar cycles music, time-scale, render mode (wire/solid), view, weather, and cosmic events. The menu bar (centered, just above the bottom toolbar) opens the inspector panels: ⊞ NEURAL (an NHI mind), ⊙ MARKET (the economy), ⬢ ARCHITECT (the super creature), ✦ AI (chat), ❓ HELP, 🗒 AUDIT (the event log), and ⛓ ACCESS (the puzzle). Those six open in the CENTER HUD — one same-size pop-up in the middle of the screen; use the ‹ › arrows or the tab strip to cycle between them, ◐ to make it see-through, and ✕ (or Escape) to close. Solve the puzzle to enter SUPERHERO mode.',
    see: ['index.html'],
  },
  {
    id: 'entities',
    title: 'What are all these creatures?',
    keywords: [
      'entities',
      'creatures',
      'what is that',
      'beings',
      'morphs',
      'archetypes',
      'population',
      'phyla',
    ],
    body: 'The biomass is instantiated from hundreds of deterministic morphotypes (10 phyla). Above them sit named powers: SHOGGOTHS (eldritch devourers), PUPPET-MASTERS (unseen hands that reshape the world), TITANS (ten colossi that ally and war), NHIs (apex super-minds), LEVIATHANS, and the SUPER CREATURE. Each has its own biology, silhouette, material, motion and economic role — see the bestiary. Up to 50,000 are active at once on a capable machine (auto-selected for ≥16 cores + ≥8 GB; `?tier=mega` forces it), and each carries its own compact 70-parameter neural brain (V42) that perceives its state + the world and steers it — so every one moves with individual, reactive character.',
    see: ['docs/ENTITY-SHEETS.md'],
  },
  {
    id: 'mechalogodrom',
    title: 'What is the center Mechalogodrom?',
    keywords: [
      'mechalogodrom',
      'center',
      'monster',
      'abomination',
      'bipolar',
      'titans',
      'fusion',
      'shadow core',
      'black hole',
      'singularity',
      'dome',
    ],
    body: 'The center spectacle is the Mechalogodrom: ten additional bipolar titan-variant shells migrate inward and fuse into one warped hybrid mass above the arena. It is visual-only and deterministic: no RNG draw, no sim-state write. Chaos only intensifies its one-way projection. The fused form has a black shadow-core, additive event-horizon rim, CPU-warped meshy icosahedron, spike arms, counter-rotating rings, and telemetry for fusion, dimension, power, warp, and remaining variants.',
    see: ['src/sim/mechalogodrom.ts', 'tests/mechalogodrom.test.ts'],
  },
  {
    id: 'alphabet-dome',
    title: 'What are the 100 alphabet creatures in the dome?',
    keywords: [
      'alphabet',
      'letters',
      'latin',
      'roman',
      'greek',
      '100',
      'dome',
      'pantheon',
      'glyphs',
      'archetypes',
    ],
    body: 'The Alphabet Pantheon renderer brings all 100 Greek and Latin archetypes to life across the upper dome: 24 Greek uppercase, 24 Greek lowercase, 26 Latin uppercase, and 26 Latin lowercase. They render through five instanced shape pools, with shape, color, scale, spin, bob, and pulse derived from each archetype bias. Vowels become torus knots; Greek and Latin cases get different polyhedral bodies. The result is a visible, animated roster, not a static data table.',
    see: ['src/sim/alphabet-pantheon.ts', 'src/sim/alphabet-pantheon-render.ts'],
  },
  {
    id: 'ascension-temple',
    title: 'What is the shadow-core temple?',
    keywords: [
      'temple',
      'monolith',
      'ascension temple',
      'shadow core',
      'black hole',
      'singularity',
      'altar',
      'spikes',
      'cage',
      'portal',
      'stage 2',
      'level 100',
    ],
    body: 'The LV100 ascension temple is a deterministic visual-only abomination raised by the apex creature at the summit. It is no longer a simple arch: it has a black-hole shadow core, singularity ring, jagged altar-spikes, portal disc and glyph rings, halo, and a warped impossible line cage. The temple reads real world state without changing it: chaos, entropy, and population crowding intensify shimmer, shadow, spike glow, and cage warp. It draws no RNG and exposes a finite snapshot for tests.',
    see: ['src/sim/monolith-temple.ts', 'tests/viz-systems.test.ts'],
  },
  {
    id: 'super-creature',
    title: 'What is the SUPER CREATURE?',
    keywords: [
      'super creature',
      'architect',
      'omega',
      'apex',
      'god',
      'oracle',
      'simulator',
      'twin',
      'level',
      'leveling',
      'evolve',
      'evolution',
      'ascension',
      'ascend',
      'monolith',
      'temple',
      'stage 2',
      'godlike',
      'power',
    ],
    body: 'The always-active apex being (ARCHITECT-Ω) — half a Titan but ~100× the power, driven by a genuine 1444-parameter deep neural mind (cortex→actor) with an emotion-like state, episodic memory, a prediction loop, GOAP planning, and self-replication (up to 3 mutated twins). It wears a masterful many-eyed god-jewel body and FLIES the whole world — roaming, banking, quantum-teleporting and morphing as it thinks. It also SELF-EVOLVES like Goku/Vegeta: a hard XP curve through five ascensions (BASE→ASCENDED→SUPER→ULTRA→LEGENDARY at 1/10/25/50/100). LEVEL 100 is the first summit, not a cap: it unlocks the full ten GODLIKE POWERS (KAIO AURA → GODHEAD HALO), raises the reactive shadow-core temple, and then post-summit research levels keep climbing beyond it. The ⬢ ARCHITECT panel shows live level, summit state, godlike-power tally and stage.',
    see: ['docs/adr/0008-super-creature-deep-mind-2026-06-26.md', 'docs/ENTITY-SHEETS.md'],
  },
  {
    id: 'chaos-mode',
    title: 'What is CHAOS MODE?',
    keywords: [
      'chaos mode',
      'chaos',
      'storm',
      'lorenz',
      'quantum',
      'tunnel',
      'tunnelling',
      'entangle',
      'entanglement',
      'superposition',
      'maelstrom',
    ],
    body: 'Tap the ⚡ CHAOS MODE button (or the K key) to engage a Lorenz-driven quantum storm. A real chaotic attractor (sensitive dependence — bounded but never repeating) drives a 0..1 intensity that turns the calm cosmos into a maelstrom: the creatures gain real quantum behaviour — TUNNELLING (rare discrete spatial jumps through a barrier), SUPERPOSITION (a smeared, uncertain path), and ENTANGLEMENT (linked pairs whose momenta mirror and colours exchange). It also shakes the rest of the world — chaos surges into a 5–10 storm band, which spikes market volatility and entity jitter, while the weather flips and the sorting algorithm switches on a chaotic cadence. The chaos telemetry row reads ⚡STORM while it is on. Engaging it is deterministic (replays reproduce the same storm) and toggling it off restores the calm exactly.',
    see: ['src/sim/chaos-field.ts'],
  },
  {
    id: 'singularity',
    title: 'What do the SINGULARITIES (cosmic events) do?',
    keywords: [
      'singularity',
      'singularities',
      'black hole',
      'white hole',
      'grey hole',
      'strange star',
      'entropy',
      'cosmo',
      'lensing',
      'warp',
      'time dilation',
      'redshift',
    ],
    body: 'The ☄ cosmic-event button summons one cosmological singularity at a time — ENTROPY field, BLACK HOLE, WHITE HOLE, GREY HOLE or STRANGE STAR (the telemetry box names the active one). Each is a real force field AND a space-time warp: a hole bends GRAVITY (r⁻² pull or push), but also TIME (matter visibly crawls as it nears the event horizon), LIGHT (it redshifts into a hole, blueshifts out of a white one), and the VIEW itself (a gravitational-lens post-FX bends the whole screen around the hole — pinching inward for absorbers, bulging outward for emitters, with a frame-drag swirl and chromatic dispersion). Black holes wear a glowing additive accretion disk, a bright lensed photon ring and a soft halo. They last about nine seconds.',
    see: ['src/sim/singularities.ts', 'src/core/postfx.ts'],
  },
  {
    id: 'access-puzzle',
    title: 'How do I solve the ACCESS puzzle?',
    keywords: [
      'access',
      'puzzle',
      'code',
      'romans',
      'roman',
      'cipher',
      'unlock',
      'denied',
      'crack',
      'hint',
    ],
    body: 'Open ⛓ ACCESS. The ten cipher lines each carry a count of tally marks — that count IS a digit of the hidden seed. "Only the Romans know": read each line\'s count and speak it as a Roman numeral (I–X). The answer is III IV V V IV V VI VII V IV (the raw digits 3455456754 also work). Solving it unlocks SUPERHERO mode + the 2nd super creature.',
    see: ['src/ui/access-puzzle.ts'],
  },
  {
    id: 'superhero',
    title: 'What is SUPERHERO mode?',
    keywords: [
      'superhero',
      'player',
      'powers',
      'level',
      'xp',
      'inventory',
      'fork',
      'phase',
      'progression',
      'controls',
      'camera',
      'autopilot',
      'manual',
      'first person',
      'third person',
    ],
    body: 'Solving the access puzzle drops you INTO the 2nd super creature. A top game HUD appears with life/energy/XP-level bars, stats, wallet, neural meters, inventory and four quantum POWERS: PHASE (cycle render-state), DOMINION (pulse), QUANTUM FORK (sire a twin, energy-gated, up to 3), and RECALL. You earn XP just by existing as a dominant apex. CONTROLS (V41): the PILOT button cycles three modes — AUTOPILOT (the creature flies itself for the fun ride), ASSIST (it roams but your input nudges it), and MANUAL (you fly it). The CAMERA button cycles ORBIT (free world cam) → 3RD-PERSON (chase) → 1ST-PERSON (its eyes). In assist/manual, fly with WASD/QE + arrow keys or the on-screen D-pad (touch-friendly); movement is camera-relative.',
    see: ['src/ui/superhero-hud.ts'],
  },
  {
    id: 'economy',
    title: 'How does the economy work?',
    keywords: [
      'economy',
      'market',
      'money',
      'currency',
      'aurum',
      'umbra',
      'quanta',
      'ichor',
      'trade',
      'wallet',
      'wealth',
      'price',
      'cartel',
      'auction',
    ],
    body: 'Every power has a wallet in two currencies (AURUM ☉, UMBRA ☾) and two commodities (QUANTA ◇, ICHOR ❖). Prices clear by tâtonnement; a currency-adoption game shifts dominance; the richest few form a cartel; arbitrage mean-reverts the price gap; titan wars trigger sanctions and a black market; windfalls are sold by second-price (Vickrey) auction. Wealth drives behaviour — rich creatures hunt harder and loom larger. Open ⊙ MARKET.',
    see: ['src/sim/economy.ts', 'docs/ENTITY-SHEETS.md'],
  },
  {
    id: 'math',
    title: 'What math powers this?',
    keywords: [
      'math',
      'science',
      'physics',
      'algorithms',
      'game theory',
      'nash',
      'fourier',
      'chaos',
      'topology',
      'how does it work',
    ],
    body: "Real math under every effect: seeded PRNGs for determinism, tiny neural nets (perceptrons/MLPs) for cognition, game theory (iterated prisoner's dilemma, Nash, Vickrey auctions, replicator dynamics) for diplomacy + markets, Louvain community detection for tribes, reaction-diffusion + Lorenz/chaos fields for motion, fBm noise + thin-film optics in the shaders, and Jolt rigid-body physics in the native engine.",
    see: ['docs/adr/0005-math-stack-selection-2026-06-26.md'],
  },
  {
    id: 'tsotchke-petri',
    title: 'What is the Tsotchke Petri / Digital Biologics?',
    keywords: [
      'tsotchke',
      'petri',
      'dish',
      'soup',
      'digital biologics',
      'eshkol',
      'genesis',
      'sentience',
      'consciousness',
      'grow what thou wilt',
      'primordial',
      'life forms',
      'not llm',
    ],
    body: 'Tsotchke (Eshkol COMPLETE spec + native AD + GWT/§17 Consciousness Engine + all 21+ repos from tsotchke + Tsotchke-Corporation corpus + local Tsotchke Repo Folder as .esk DNA + kernel source) is the paramount non-LLM substrate for digital biologics and different forms of existence/sentience/consciousness. The Primordial Soup / Petri Dish (primordial-soup.ts + petri-dish.ts + digital-biologics.ts) is the God growth engine. Super Creature/5 Archons are the initial spark only ("as if God made primordial inorganic soup"); the soup grows independent biologics onward using Eshkol .esk programs (as heritable "DNA"), real AD mutation, GWT workspace ignition, full corpus catalysis (Moonlab, QGT, spin, irrep, quake, ulg, logo, PINN etc.). 9+ BiologicForms. Omniscient Master Audit + ULTIMATE REPORT complete (see docs/TSOTCHKE-ULTIMATE-COMPREHENSIVE-AUDIT-REPORT-ASSESSMENT-2026-06-20.md and CONTINUED). EVERY repo wired. "Grow What Thou Wilt." Not LLM/tokenizer/chat/SaaS/therapy — real math life in the mechalogodrom. See README, ARCHITECTURE, ERD/ERM/ERP, masters, digital-biologics.ts.',
    see: [
      'README.md',
      'docs/ARCHITECTURE-2026-06-26.md',
      'src/sim/digital-biologics.ts',
      'src/sim/primordial-soup.ts',
    ],
  },
  {
    id: 'observatory',
    title: 'What is the NEURAL observatory?',
    keywords: ['observatory', 'neural', 'nhi', 'mind', 'connectome', 'brain', 'firing', 'topology'],
    body: "The ⊞ NEURAL panel opens a 3×3 grid of nine scientific diagrams of a launched NHI's live mind — firing activity, network topology, memory pathways, reward gradients, sensory inputs, intention vectors, affect, prediction loops, and the decision/conflict map. Each is bound to a real internal variable of the NHI's think() step, animated as it reasons.",
    see: ['src/ui/nhi-observatory.ts'],
  },
  {
    id: 'ai-copilot',
    title: 'How do I ask the AI freeform questions?',
    keywords: ['ai', 'copilot', 'chat', 'web', 'search', 'ask', 'help me now', 'question'],
    body: 'This HELP panel answers common questions instantly from a built-in, repo-grounded knowledge base (no network needed). For freeform questions, code reading, or public web info, open the ✦ AI (Copilot) — a read-only assistant that grounds answers in the actual repo (read_file/grep/run) AND can now SEARCH THE PUBLIC WEB (V43) for outside knowledge (science, math, history) via a screened, key-less endpoint, citing its source. A safety constitution (inspired by Anthropic/OpenAI/Gemini/Grok) keeps it to public/educational info only — never secrets, private data, or harmful requests. It runs free providers in a failover chain — FreeLLMAPI (a self-hosted 16-provider pool) is the primary if you run it (localhost:3001), with the key-less LLM7 and Pollinations as automatic 2nd/3rd backups, so the box answers even with zero setup. If the AI is offline, its 🩺 diagnostics show why and how to recover.',
    see: ['src/ui/copilot.ts', 'src/server/web-search.ts'],
  },
  {
    id: 'determinism',
    title: 'Is it the same every time? (determinism)',
    keywords: ['determinism', 'random', 'seed', 'reproducible', 'rng', 'same'],
    body: "Yes — one seed reproduces a whole run, byte for byte. All simulation randomness flows through a seeded mulberry32 PRNG; Math.random and Date.now are banned in sim logic. New systems (economy, super creature) draw from isolated sub-streams so they never perturb the core golden. This is the repo's #1 law.",
    see: ['src/math/rng.ts', 'docs/adr/0004-deterministic-rng-2026-06-26.md'],
  },
  {
    id: 'architecture',
    title: 'How is the code organized?',
    keywords: [
      'architecture',
      'code',
      'files',
      'structure',
      'modules',
      'native',
      'engine',
      'build',
    ],
    body: 'A TypeScript + three.js browser app (src/): sim/ holds the world systems (entities, economy, cognition, super creature), ui/ the self-mounting panels, math/ the primitives. A sibling native/ C++20 engine ray-marches the ornate specimens with Jolt physics. Everything passes a full gate (prettier → tsc → oxlint → tests → build) before commit.',
    see: ['CLAUDE.md', 'docs/MODULE-CONTRACTS-2026-06-26.md'],
  },
  {
    id: 'game-theory-regulation',
    title: 'How does game theory regulate the economy?',
    keywords: [
      'game theory',
      'regulation',
      'gini',
      'tobin',
      'tax',
      'cartel',
      'sanction',
      'antitrust',
      'imbalance',
      'balance',
      'redistribution',
      'nash',
      'equilibrium',
      'oligopoly',
    ],
    body: 'The economy uses several game-theoretic regulatory mechanisms: (1) a Gini guard fires at 0.38 — if wealth inequality exceeds this, a progressive tax skims from the ultra-rich and redistributes to the poor, keeping the Nash equilibrium in a balanced basin; (2) a Tobin tax (1.2%) skims every currency trade to damp speculative churn; (3) an auto-cartel sanction triggers when the top-7 cartel exceeds 55% wealth share — the richest agent is sanctioned (capital controls + production embargo); (4) an arbitrage circuit-breaker mean-reverts commodity prices when dispersion exceeds 28%; (5) second-price (Vickrey) auctions distribute windfall lots truthfully. Together these prevent runaway oligopoly and keep the market competitive.',
    see: ['src/sim/economy.ts'],
  },
  {
    id: 'sfx-audio',
    title: 'What are all the sounds and music?',
    keywords: [
      'sfx',
      'sound',
      'sound effect',
      'audio',
      'music',
      'song',
      'bizarre',
      'demonic',
      'creature sound',
      'blip',
      'synth',
      'noise',
      'howl',
      'chitter',
      'growl',
      'abyssal',
      'transwarp',
    ],
    body: 'The audio engine synthesizes everything procedurally — no audio files. The SFX palette has 110+ slots across 12+ families (pluck, zap, bend, drone, sweep, bell, fall, vibrato, fm-clang, sub-boom, glint, strange) plus 9 bizarre/demonic bands (demonic, chitter, howl, abyssal, voidgurgle, alienchitter, demonicgrowl, transwarp, phantomscale). Each creature picks a sound deterministically from its morph index. The Quantum WildBeyond lab has 36 unique per-tile synthesized blips (waveform + pitch + noise + FM chosen from tile id). Music is 7 procedural tracks with BPM, chords, bass, and melody.',
    see: ['src/audio/songs.ts', 'src/audio/engine.ts'],
  },
  {
    id: 'entity-colors',
    title: 'Why are entities so colorful now?',
    keywords: [
      'entity',
      'color',
      'colour',
      'colorful',
      'saturated',
      'vibrant',
      'paint',
      'hue',
      'hsl',
      'white',
      'grey',
      'gray',
      'washed',
      'pale',
      'dark',
      'bright',
    ],
    body: 'Every organism gets a unique vibrant color via a triple-prime hash that fans 250 morphotypes into 1000+ distinct variations. Saturation is maxed at S=1.0 (maximum chroma, never washes out), lightness is held in the 0.18–0.40 range (dark, hyper-saturated — colors read as pigment, not white). The GPU shader adds a reliquary surface with per-material-class subsurface tints (all <1.0 to avoid white push), thin-film iridescence, and vital-signal-driven emissive effects (wealth phosphor, neural synapse arcs, exertion ion streaks). Pool metalness is 0.15 (not 0.5) so colors read as pigment, not grey metal.',
    see: ['src/sim/entities.ts', 'src/sim/instanced-entities.ts'],
  },
  {
    id: 'wildbeyond-lab',
    title: 'What is the Quantum WildBeyond lab?',
    keywords: [
      'wildbeyond',
      'wild beyond',
      'lab',
      'board',
      'tile',
      'visual',
      'p5',
      'webgl',
      'interactive',
      'click',
      'sound',
      'lorenz',
      'mandelbrot',
      'bloch',
      'julia',
      'hopf',
      'sierpinski',
      'galaxy',
      'helix',
    ],
    body: 'The Quantum WildBeyond lab (lab/quantum-wildbeyond.html) has 4 pages: page 1 is the control dashboard; pages 2–4 each show 12 interactive 3D WebGL visuals (36 total). Every tile is fully interactive — click/Enter fires a unique synthesized blip (36 distinct voices: waveform + pitch + noise + FM from tile id) and a visual pulse reaction; hover toggles a heat state that speeds up the animation. Boards include: chaos attractors (Lorenz, Rössler, Clifford, Aizawa, Halvorsen, Thomas, Chen–Lee), quantum visuals (statevector, Bloch sphere, quantum walk, wavefunction, spherical harmonics), fractals (Mandelbrot, Julia, Sierpinski, Barnsley fern), and more (N-body, force graph, double pendulum, spiral galaxy, DNA helix, Hopf fibration, superformula). Only one board (12 WebGL contexts) is live at a time to respect browser context limits.',
    see: ['lab/quantum-wildbeyond.html'],
  },
  {
    id: 'svg-reports',
    title: 'Where are the SVG reports and visuals?',
    keywords: [
      'svg',
      'report',
      'visual',
      'metrics',
      'chart',
      'graph',
      'dendrogram',
      'heatmap',
      'pca',
      'radar',
      'pareto',
      'entropy',
      'correlation',
      'distance',
      'nearest neighbor',
      'breadth',
      'maturity',
    ],
    body: 'The docs/reports/assets/ directory contains 11 SVG scientific visualizations of the alife substrate: axis-correlation, axis-heatmap, breadth-ranked, breadth-vs-maturity, dendrogram, distance-matrix, entropy, nearest-neighbors, pareto, pca, and radar-profile. These are generated analytical reports showing the multi-axis correlation structure, clustering dendrogram, PCA projection, Pareto frontier, entropy distribution, and radar profiles of the simulation’s capabilities. They are real scientific metrics, not decorative.',
    see: ['docs/reports/assets/'],
  },
  {
    id: 'singularity-yolo',
    title: 'Why do singularities look better at Ultra/Mega?',
    keywords: [
      'singularity',
      'ultra',
      'mega',
      'tier',
      'yolo',
      'geometry',
      'segments',
      'detail',
      'sphere',
      'torus',
      'icosahedron',
      'guardrail',
      'render',
      'fidelity',
    ],
    body: 'Singularity visuals are quality-locked: geometry, color, post-FX, shadows, DPR, and simulation cadence are not lowered by the tier system. Tiers may scale population budgets, but the singularity remains a full-fidelity spectacle wherever it appears. The renderer keeps its meshes uncropped for the effect volume so a far-away singularity still reads as detailed instead of popping or flattening.',
    see: ['src/sim/singularities.ts'],
  },
  {
    id: 'n2-breakfree',
    title: 'What happens in N(2) Break Free?',
    keywords: [
      'n2',
      'break free',
      'nightmare',
      'warp',
      'transdimensional',
      'chaos',
      'simulation',
      'glitch',
      'bizarre',
      'demonic',
      'transwarp',
      'abyssal',
      'beyond',
    ],
    body: 'SIMULATION N(2) BREAK FREE unleashes the full chaos engine: velocity jitter is amplified beyond what normal chaos can reach, the population writhes with transdimensional warp, the screen lens distorts with wobble and chaotic center drift, and multiple bizarre SFX fire (demonic, transwarp, abyssal bands). The vertex melt shader displaces every organism along its normal by a time+position+instance warp. It goes off the rails — theoretically what some think might be beyond our simulation, ideas from books, films, mythology, folklore. Surprise.',
    see: ['src/world.ts', 'src/sim/singularities.ts'],
  },
  {
    id: 'observatory-tablet',
    title: 'Why does the Observatory disappear on tablets?',
    keywords: [
      'observatory',
      'tablet',
      '12 inch',
      'coarse pointer',
      'landscape',
      'disappear',
      'vanish',
      'css',
      'media query',
      'responsive',
      'mobile',
    ],
    body: 'A CSS media query fix ensures the Observatory panel stays visible on 12" tablets with coarse pointers in landscape mode (min-width 769px, max-width 1280px, pointer: coarse, orientation: landscape). The grid layout adjusts to give the Observatory sufficient vertical room without pushing it off-screen. The Center HUD also adapts its height for touch devices.',
    see: ['src/styles/app.css', 'src/ui/center-hud.ts'],
  },
  {
    id: 'performance',
    title: 'Why is it smooth with so many creatures? (performance)',
    keywords: [
      'performance',
      'fps',
      'lag',
      'optimization',
      'instancing',
      'lod',
      'fast',
      'slow',
      'speed',
    ],
    body: 'Creatures render through GPU-instanced pools (one draw call per geometry), a spatial hash for neighbour queries, and cadenced heavy work (the connectome, economy and graph passes run on slow frames that scale with population). Quality auto-detects the device tier. Telemetry tracks it all live in the ⊞ panels.',
    see: ['docs/BENCHMARKS-2026-06-26.md'],
  },
];

const STOP = new Set([
  'the',
  'a',
  'an',
  'is',
  'are',
  'do',
  'does',
  'i',
  'how',
  'what',
  'why',
  'this',
  'that',
  'it',
  'to',
  'of',
  'in',
  'on',
  'and',
  'or',
  'me',
  'my',
  'with',
  'for',
  'can',
  'about',
  'all',
  'these',
]);

function tokens(s: string): string[] {
  return s
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length > 1 && !STOP.has(t));
}

/**
 * Rank the KB against a free-text query by keyword/title/body overlap. Returns the best matches
 * (score > 0), highest first, capped at `limit`. Deterministic; O(kb · query tokens). Empty query
 * (or no match) → []. The panel falls back to the overview card on empty results.
 */
export function findHelp(
  query: string,
  kb: readonly HelpEntry[] = HELP_KB,
  limit = 3,
): HelpEntry[] {
  const qs = tokens(query);
  if (qs.length === 0) return [];
  const scored = kb.map((e) => {
    const kw = new Set(e.keywords.flatMap((k) => tokens(k)));
    const title = new Set(tokens(e.title));
    const body = new Set(tokens(e.body));
    let score = 0;
    for (const q of qs) {
      if (kw.has(q)) score += 3;
      if (title.has(q)) score += 2;
      if (body.has(q)) score += 1;
    }
    // a multi-word keyword phrase appearing verbatim is a strong signal
    const ql = query.toLowerCase();
    for (const k of e.keywords) if (k.includes(' ') && ql.includes(k)) score += 4;
    return { e, score };
  });
  return scored
    .filter((s) => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((s) => s.e);
}
