/**
 * Generate docs/FILE-MAP.md — a self-maintaining map of the codebase, one row per module, summarised
 * from each file's OWN leading doc-comment. Run via `bun scripts/gen-filemap.ts` (also wired into the
 * RAG book). Deterministic (sorted), so re-running on an unchanged tree is a no-op diff. No hand edits:
 * to fix a summary, fix the module's header and re-run. Part of the DOCUMENTATION / RAG BOOK (V37).
 */
import { Glob } from 'bun';

const ROOT = 'src';

/** Pull a one-line summary from a module: the first content line of its leading block/line comment. */
function summarize(text: string): string {
  const block = text.match(/\/\*\*([\s\S]*?)\*\//);
  if (block) {
    const lines = (block[1] ?? '').split('\n').map((l) => l.replace(/^\s*\*\s?/, '').trim());
    const first = lines.find((l) => l.length > 0);
    if (first) return first.length > 160 ? first.slice(0, 157) + '…' : first;
  }
  const line = text.match(/^\s*\/\/\s*(.+)$/m);
  return line ? (line[1] ?? '—').trim() : '—';
}

const rels = [...new Glob('**/*.ts').scanSync(ROOT)].map((r) => r.replace(/\\/g, '/')).sort();

const groups = new Map<string, { file: string; sum: string }[]>();
for (const rel of rels) {
  const slash = rel.lastIndexOf('/');
  const dir = slash >= 0 ? `${ROOT}/${rel.slice(0, slash)}` : ROOT;
  const file = slash >= 0 ? rel.slice(slash + 1) : rel;
  const sum = summarize(await Bun.file(`${ROOT}/${rel}`).text());
  const arr = groups.get(dir) ?? [];
  arr.push({ file, sum });
  groups.set(dir, arr);
}

let out = `# File Map — the codebase, module by module\n\n`;
out +=
  `_Auto-generated by \`bun scripts/gen-filemap.ts\` from each module's own doc-header — **do not edit ` +
  `by hand**, fix the module header and re-run. ${rels.length} TypeScript modules across ` +
  `${groups.size} directories. The sibling C++ engine lives in \`native/src/\` (see ` +
  `[ADR-0007](./adr/0007-native-cpp-engine-and-live-physics.md))._\n\n`;

for (const dir of [...groups.keys()].sort()) {
  out += `## \`${dir}/\`\n\n| Module | What it does |\n| --- | --- |\n`;
  for (const { file, sum } of groups.get(dir) ?? []) {
    out += `| \`${file}\` | ${sum.replace(/\|/g, '\\|')} |\n`;
  }
  out += `\n`;
}

await Bun.write('docs/FILE-MAP.md', out);
console.log(`wrote docs/FILE-MAP.md — ${rels.length} modules, ${groups.size} dirs`);
