/**
 * Bake ALife SVG files into a TS module so Docs/Spec gallery works on GitHub Pages,
 * Cursor preview, and any static host — zero network fetch required.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';

const ASSETS = new URL('../docs/reports/assets/', import.meta.url);
const OUT = new URL('../src/generated/alife-svg-embed.ts', import.meta.url);

const files = (await readdir(ASSETS)).filter((f) => f.startsWith('alife-') && f.endsWith('.svg'));
const entries: string[] = [];
for (const f of files.sort()) {
  const svg = await readFile(new URL(f, ASSETS), 'utf8');
  entries.push(`  ${JSON.stringify(f)}: ${JSON.stringify(svg)},`);
}

await mkdir(new URL('../src/generated/', import.meta.url), { recursive: true });
const body =
  `/** AUTO-GENERATED by scripts/gen-alife-embed.ts — do not edit by hand. */\n` +
  `export const ALIFE_SVG_EMBED: Readonly<Record<string, string>> = {\n` +
  entries.join('\n') +
  `\n};\n`;
await writeFile(OUT, body, 'utf8');
console.log(`embedded ${files.length} ALife SVGs -> src/generated/alife-svg-embed.ts`);
