#!/usr/bin/env bun
/**
 * HARVEST TSOTCHKE CORPUS — proof that we BUILD WITH the local Tsotchke folder.
 *
 * This script is run at dev/build time (or manually) to consume the real
 * Tsotchke Repo Folder (Z:\[Vibe Coded (AI)]\(Tsotchke)) as the source of truth
 * for digital biologics "DNA".
 *
 * It scans for .esk programs (Eshkol's heritable consciousness code) and
 * key kernel markers from the mirrors, then emits a generated module that
 * primordial-soup + digital-biologics can import for authentic seeding.
 *
 * This is not an LLM/tokenizer path. This is using the actual Eshkol + Moonlab +
 * QGT + spin + libirrep + ... corpus to grow different forms of life.
 *
 * "Grow What Thou Wilt." — Aleister Crowley
 * Masters: Broly finish, Starkiller contracts, Manhattan measurement.
 */

import { readdirSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, relative } from 'path';

const TSOTCHKE_BASE = 'Z:\\[Vibe Coded (AI)]\\(Tsotchke)';
const OUT_DIR = 'src/sim';
const OUT_FILE = join(OUT_DIR, 'generated-tsotchke-seeds.ts');

interface Harvest {
  eskCount: number;
  eskSamples: string[];
  totalScanned: number;
  timestamp: string;
  note: string;
}

function harvest(): Harvest {
  let eskCount = 0;
  const eskSamples: string[] = [];
  let total = 0;

  const candidates = [join(TSOTCHKE_BASE, 'Eshkol', 'eshkol_repo'), join(TSOTCHKE_BASE, 'Eshkol')];

  for (const base of candidates) {
    if (!existsSync(base)) continue;
    try {
      const walk = (dir: string) => {
        // Sort by name: readdirSync order is filesystem-dependent, but this harvest
        // emits ESK_SAMPLE_PROGRAMS into generated source — the sample set (and the
        // committed output) must be reproducible across machines/OSes.
        const ents = readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
          a.name < b.name ? -1 : a.name > b.name ? 1 : 0,
        );
        for (const e of ents) {
          const p = join(dir, e.name);
          if (e.isDirectory()) {
            walk(p);
          } else {
            total++;
            if (e.name.endsWith('.esk')) {
              eskCount++;
              if (eskSamples.length < 8)
                eskSamples.push(relative(TSOTCHKE_BASE, p).replace(/\\/g, '/'));
            }
          }
        }
      };
      walk(base);
    } catch (error) {
      const detail = error instanceof Error ? error.message : String(error);
      throw new Error(`[harvest-tsotchke] Failed while scanning ${base}: ${detail}`);
    }
    // The first existing candidate (Eshkol/eshkol_repo) already contains every .esk file;
    // its parent (Eshkol) recursively re-enters eshkol_repo, so walking both double-counts
    // every file. Stop after the first successfully scanned existing base; a traversal error
    // aborts instead of emitting a plausible-looking partial census.
    break;
  }

  return {
    eskCount,
    eskSamples,
    totalScanned: total,
    // DETERMINISTIC provenance — a wall-clock timestamp here was baked into the git-tracked
    // generated file, so every `bun dev` produced a spurious diff and a non-reproducible artifact.
    // Derive it from the corpus census instead: it changes only when the corpus actually changes.
    timestamp: `corpus:${eskCount}esk/${total}files`,
    note: 'Harvested directly from local Tsotchke Repo Folder at build time. Eshkol .esk programs are the heritable substrate for digital biologics sentience. All other Tsotchke mirrors (moonlab, libirrep, QGT, spin, quake, etc.) provide the additional physics/geometry/order kernels.',
  };
}

function emit(h: Harvest): void {
  // CLOBBER GUARD: when the external Tsotchke drive is absent the harvest is empty. Overwriting the
  // git-tracked generated file with empty arrays would silently wipe the committed ESK_DERIVED_SEEDS
  // that seed primordial-soup / digital-biologics — a non-erroring change of sim behavior on any
  // clone without the drive. Keep the committed seeds intact instead.
  if (h.eskCount === 0 && existsSync(OUT_FILE)) {
    console.warn(
      `[harvest-tsotchke] No .esk programs found (corpus drive absent?) — keeping committed ${OUT_FILE} rather than clobbering it with an empty harvest.`,
    );
    return;
  }
  if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

  const content = `// AUTO-GENERATED by scripts/harvest-tsotchke-corpus.ts
// DO NOT EDIT BY HAND — run the harvest script (or include in build) after changes to the local Tsotchke corpus.
// Source: ${TSOTCHKE_BASE}
// This file makes Cosmogonic actually BUILD WITH the Tsotchke Repo Folder.

export const TSOTCHKE_HARVEST = ${JSON.stringify(h, null, 2)} as const;

export const ESK_SAMPLE_PROGRAMS: readonly string[] = ${JSON.stringify(h.eskSamples, null, 2)};

// Convenience: a small set of numeric "genomes" derived from real .esk file name hashes.
// These can seed primordial-soup / digital-biologics with authentic Eshkol DNA.
export const ESK_DERIVED_SEEDS: readonly number[] = ${JSON.stringify(
    h.eskSamples.map((s) => {
      let h = 0x811c9dc5;
      for (let i = 0; i < s.length; i++) h = ((h ^ s.charCodeAt(i)) * 0x01000193) >>> 0;
      return h >>> 0;
    }),
    null,
    2,
  )};

export function getEshkolProgramFingerprint(index: number): number {
  return ESK_DERIVED_SEEDS[index % ESK_DERIVED_SEEDS.length] ?? 0x50ff0001;
}
`;

  writeFileSync(OUT_FILE, content, 'utf8');
  console.log(`[harvest-tsotchke] Wrote ${OUT_FILE}`);
  console.log(`  .esk programs found: ${h.eskCount}`);
  console.log(`  samples: ${h.eskSamples.slice(0, 3).join(', ')}...`);
}

const data = harvest();
emit(data);
console.log('Tsotchke corpus harvest complete. Wired as build source.');
