/**
 * APEX Parameter Manifold — the honest, deterministic scaffolding that scales the APEX #101 brain
 * toward **one billion parameters**.
 *
 * The APEX engine ({@link ../sim/apex-brain}) already declares a ≥1e9 DESIGNED neuron budget at the
 * `MASSIVE` / `APEX-1B` scale, while the live JS runtime caps organ allocation at `LIVE_NODE_CAP`.
 * That is honest but incomplete: it reports a target without a substrate that can actually *address*
 * or *compute over* a billion parameters. This module supplies that substrate.
 *
 * It splits the parameter budget across five tiers, each backed by a real representation strategy, so
 * a billion parameters become genuinely reachable without pretending to allocate 4 GB of floats in a
 * browser tab:
 *
 * 1. **procedural** — connectivity that is *generated by a deterministic rule*, not stored (the
 *    prime-sieve twin-prime edge law, Cantor-dust addressing, Klein-bottle adjacency). Billions of
 *    edges are addressable by predicate; any slice materialises on demand from a seed. (Aaronson &
 *    Gottesman-style implicit structure — the count is real, the storage is O(1).)
 * 2. **quantum-effective** — the Quantum Brain's *effective Hilbert dimension*. A stabilizer register
 *    of `q` qubits (Gottesman-Knill / {@link ../math/clifford-tableau}) addresses a `2^q`-dimensional
 *    state space with O(q²) stored bits; `q = 30` reaches 2³⁰ ≈ 1.07e9. This is the physics-grounded
 *    billion anchor — real quantum information, not decoration.
 * 3. **resident-field** — the field organs (acoustic wave, heat, Klein diffusion, tunnel amplitude)
 *    are 2-D stencils → GPU textures. Millions of texels are *resident* on the graphics GPU and
 *    stepped in parallel (the CPU reference stencil lives in {@link ../sim/apex-field-substrate}).
 * 4. **resident-dense** — the genuinely dense state (pendulum rotors, delay rings) sharded into
 *    typed-array blocks materialised up to a device memory budget; any shard is reproducible from the
 *    seed ({@link materializeDenseShard}), so the design streams instead of allocating all at once.
 * 5. **native-declared** — the remaining designed budget a native C/C++ backend would hold. It is a
 *    *reproducing* backend (ADR-0007): the TS engine stays authoritative and the native kernels must
 *    match its same-seed hashes ({@link ../sim/apex-native-backend}); nothing here is live-allocated.
 *
 * The reportable quantities are therefore honest and distinct: `designedParams` (architecture target,
 * ≥1e9), `addressableParams` (reachable this run — procedural + quantum dims + resident), and
 * `residentParams` (actually materialised, bounded by the device budget). NOT a sentience claim; a
 * scaling-substrate claim (doctrine Level 3-4). Deterministic, DOM-free, allocation-aware.
 *
 * @see docs/APEX-1B-SUBSTRATE-ARCHITECTURE-2026-07-01.md
 * @see docs/APEX-BRAIN-ABOMINATION-2026-06-26.md
 */

import { mulberry32 } from '../math/rng';
import { APEX_BRAIN_TARGET_NEURONS, apexDesignedNeurons, type ApexScale } from './apex-brain';

/** The billion-parameter architecture target the whole manifold scaffolds toward. */
export const APEX_BILLION = APEX_BRAIN_TARGET_NEURONS; // 1_000_000_000

/** Designed parameters per neuron (matches {@link ../sim/apex-brain.apexScaleParams}: neurons × 2.5). */
export const PARAMS_PER_NEURON = 2.5;

/** Floats in one materialised dense shard (4 MB @ 4 bytes/float). Streaming granularity. */
export const SHARD_FLOATS = 1 << 20; // 1,048,576

/** The five substrate tiers a designed parameter can live in. */
export type ParamTier =
  | 'procedural'
  | 'quantum-effective'
  | 'resident-field'
  | 'resident-dense'
  | 'native-declared';

/** A device's memory/compute envelope — bounds what the manifold materialises as *resident*. */
export interface DeviceProfile {
  readonly name: string;
  /** Max resident CPU floats across all dense/field tiers (the hard RAM budget). */
  readonly residentFloatCap: number;
  /** Max GPU texels a single field organ may hold (one texture edge²). */
  readonly fieldTexelCap: number;
  /** Max stabilizer qubits the Quantum Brain may reach (2^cap = effective dimension ceiling). */
  readonly stabilizerQubitCap: number;
}

/** Browser tab — conservative 256 MB resident, 4096² field textures, 30-qubit stabilizer (≥1e9 dim). */
export const DEVICE_BROWSER: DeviceProfile = {
  name: 'browser',
  residentFloatCap: 64 << 20, // 67,108,864 floats ≈ 256 MB
  fieldTexelCap: 4096 * 4096, // 16.7M texels
  stabilizerQubitCap: 30,
};

/** Workstation — 1 GB resident, 8192² fields, 32-qubit stabilizer. */
export const DEVICE_WORKSTATION: DeviceProfile = {
  name: 'workstation',
  residentFloatCap: 256 << 20, // 268,435,456 floats ≈ 1 GB
  fieldTexelCap: 8192 * 8192,
  stabilizerQubitCap: 32,
};

/** Native backend (roadmap) — the tier that actually holds the full dense billion. */
export const DEVICE_NATIVE: DeviceProfile = {
  name: 'native',
  residentFloatCap: 1_100_000_000,
  fieldTexelCap: 16384 * 16384,
  stabilizerQubitCap: 40,
};

/** Per-tier accounting: designed budget, what is addressable, and what is actually resident. */
export interface TierBudget {
  readonly tier: ParamTier;
  /** Designed/architecture parameter count contributed by this tier (may be in the hundreds of M). */
  readonly designed: number;
  /**
   * Parameters reachable this run WITHOUT full materialisation. For procedural/quantum tiers this is
   * the full designed count (rule- or register-addressable); for resident tiers it equals `resident`.
   */
  readonly addressable: number;
  /** Parameters actually materialised in memory this run (0 for procedural/native-declared). */
  readonly resident: number;
}

/** A full manifold read-out for one scale on one device. */
export interface ManifoldSnapshot {
  readonly scaleName: string;
  readonly deviceName: string;
  /** Σ designed across all tiers — the architecture target (≥1e9 at MASSIVE/APEX-1B). */
  readonly designedParams: number;
  /** Σ addressable — parameters reachable this run (procedural + quantum dims + resident). */
  readonly addressableParams: number;
  /** Σ resident — parameters actually held in memory (bounded by the device float cap). */
  readonly residentParams: number;
  /** The device's hard resident-float budget. */
  readonly deviceBudgetParams: number;
  /** Effective Hilbert dimension of the stabilizer Quantum Brain (2^stabilizerQubits). */
  readonly quantumStabilizerQubits: number;
  readonly quantumStabilizerDim: number;
  /** True when the addressable budget reaches one billion parameters. */
  readonly reachesBillion: boolean;
  /** True when the Quantum Brain alone reaches a billion-dimensional state space (≥30 qubits). */
  readonly quantumReachesBillion: boolean;
  /** How many {@link SHARD_FLOATS}-sized shards the resident-dense tier streams through. */
  readonly denseShardCount: number;
  /** Fraction of the designed budget that is resident this run (0..1) — the honesty gap made visible. */
  readonly residentFraction: number;
  readonly tiers: readonly TierBudget[];
}

/** Deterministic child-seed mix (golden-ratio salt), consistent with the sim's sub-stream style. */
function mixSeed(seed: number, salt: number): number {
  return (seed ^ Math.imul(salt >>> 0, 0x9e3779b1)) >>> 0 || 1;
}

/** Params contributed by a neuron count (rounded, matching the engine's 2.5×). O(1). */
function paramsOf(neurons: number): number {
  return Math.round(neurons * PARAMS_PER_NEURON);
}

/**
 * The stabilizer-qubit budget for a scale on a device. The effective Hilbert dimension tracks the
 * design: `q = ceil(log2(designed neurons))`, clamped to the device cap. At `APEX-1B` (~9.5e8
 * designed neurons) this yields 30 qubits → 2³⁰ ≈ 1.07e9-dimensional stabilizer reach. O(1).
 */
export function stabilizerQubitsForScale(scale: ApexScale, device: DeviceProfile): number {
  const designed = Math.max(2, apexDesignedNeurons(scale));
  const needed = Math.ceil(Math.log2(designed));
  return Math.max(scale.qubits, Math.min(device.stabilizerQubitCap, needed));
}

/**
 * Build the full parameter manifold for a scale on a device. Pure, O(1) (constant number of organs).
 *
 * Tier assignment mirrors each organ's real representation: graph/rule organs are procedural; field
 * organs are GPU-resident texels; dense-state organs shard into RAM; the qubit register is the
 * quantum-effective anchor; any overflow past the device budget is native-declared (roadmap).
 */
export function buildManifold(
  scale: ApexScale,
  device: DeviceProfile = DEVICE_BROWSER,
): ManifoldSnapshot {
  // ── Per-organ designed neuron counts (mirrors apexDesignedNeurons decomposition). ──────────────
  const proceduralNeurons = scale.loom + scale.necro + scale.slime + scale.ouroboros;
  const fieldNeurons = scale.acoustic + scale.thermo + scale.kleinW * scale.kleinH + scale.tunnel;
  const denseNeurons = scale.pendulum + (scale.chronoD2 + 1);

  const proceduralDesigned = paramsOf(proceduralNeurons);
  const fieldDesigned = paramsOf(fieldNeurons);
  const denseDesigned = paramsOf(denseNeurons);

  // ── Quantum-effective tier: dense high-fidelity core + stabilizer billion-dim reflex. ──────────
  const stabilizerQubits = stabilizerQubitsForScale(scale, device);
  const stabilizerDim = 2 ** stabilizerQubits;
  const denseQubits = Math.min(30, scale.qubits);
  const quantumDesigned = 2 ** denseQubits + stabilizerDim; // addressable state-space dimension
  const quantumResident = 2 ** denseQubits * 2; // the exact statevector actually held (re + im)

  // ── Resident bounds (all within the device float cap): the exact statevector is reserved first,
  //    then field organs fill GPU texels, then the dense state fills whatever RAM remains. ─────────
  const afterQuantum = Math.max(0, device.residentFloatCap - quantumResident);
  const fieldTexelBudget = device.fieldTexelCap * 4; // up to 4 components (RGBA) per organ texture
  const fieldResident = Math.min(fieldDesigned, fieldTexelBudget, afterQuantum);
  const denseBudget = Math.max(0, afterQuantum - fieldResident);
  const denseResident = Math.min(denseDesigned, denseBudget);

  // ── Native-declared: designed dense state that exceeds this device's resident budget. ──────────
  const nativeDeclared =
    Math.max(0, denseDesigned - denseResident) + Math.max(0, fieldDesigned - fieldResident);

  const tiers: TierBudget[] = [
    {
      tier: 'procedural',
      designed: proceduralDesigned,
      addressable: proceduralDesigned,
      resident: 0,
    },
    {
      tier: 'quantum-effective',
      designed: quantumDesigned,
      addressable: quantumDesigned,
      resident: quantumResident,
    },
    {
      tier: 'resident-field',
      designed: fieldDesigned,
      addressable: fieldResident,
      resident: fieldResident,
    },
    {
      tier: 'resident-dense',
      designed: denseDesigned,
      addressable: denseResident,
      resident: denseResident,
    },
    { tier: 'native-declared', designed: nativeDeclared, addressable: 0, resident: 0 },
  ];

  const designedParams =
    proceduralDesigned + quantumDesigned + fieldDesigned + denseDesigned + nativeDeclared;
  const addressableParams = tiers.reduce((a, t) => a + t.addressable, 0);
  const residentParams = tiers.reduce((a, t) => a + t.resident, 0);
  const denseShardCount = Math.max(1, Math.ceil(denseResident / SHARD_FLOATS));

  return {
    scaleName: scale.name,
    deviceName: device.name,
    designedParams,
    addressableParams,
    residentParams,
    deviceBudgetParams: device.residentFloatCap,
    quantumStabilizerQubits: stabilizerQubits,
    quantumStabilizerDim: stabilizerDim,
    reachesBillion: addressableParams >= APEX_BILLION,
    quantumReachesBillion: stabilizerDim >= APEX_BILLION,
    denseShardCount,
    residentFraction: designedParams > 0 ? residentParams / designedParams : 0,
    tiers,
  };
}

/**
 * Deterministically materialise dense shard `shardId` for a given seed. Fills `out` (or a fresh
 * `SHARD_FLOATS` array) with a bounded, reproducible procedural weight field in (-1, 1): the same
 * `(seed, shardId)` always yields byte-identical values, so a billion-parameter design streams shard
 * by shard instead of allocating all at once. These are procedural WEIGHTS (a deterministic function
 * of index) — never dressed-up randomness. O(SHARD_FLOATS).
 */
export function materializeDenseShard(
  seed: number,
  shardId: number,
  out?: Float32Array,
): Float32Array {
  const buf = out && out.length >= SHARD_FLOATS ? out : new Float32Array(SHARD_FLOATS);
  const rng = mulberry32(mixSeed(seed, (shardId + 0x5ade) >>> 0));
  for (let i = 0; i < SHARD_FLOATS; i++) {
    // tanh-shaped bounded weight: real parameter values, deterministic per index.
    const u = rng() * 2 - 1;
    buf[i] = Math.tanh(u * 1.5);
  }
  return buf;
}

/**
 * How many dense shards a scale streams through on a device (the resident-dense tier). O(1).
 * Streaming shard-by-shard is how the design reaches a billion resident-equivalent params over time
 * without exceeding the instantaneous device budget.
 */
export function denseShardPlan(
  scale: ApexScale,
  device: DeviceProfile = DEVICE_BROWSER,
): {
  readonly shardCount: number;
  readonly shardFloats: number;
  readonly totalDenseParams: number;
} {
  const m = buildManifold(scale, device);
  const dense = m.tiers.find((t) => t.tier === 'resident-dense');
  const total = dense ? dense.designed : 0;
  return {
    shardCount: Math.max(1, Math.ceil(total / SHARD_FLOATS)),
    shardFloats: SHARD_FLOATS,
    totalDenseParams: total,
  };
}

/** A one-line human summary of a manifold snapshot (telemetry / Architecture panel). O(1). */
export function manifoldSummary(m: ManifoldSnapshot): string {
  const b = (n: number): string =>
    n >= 1e9 ? `${(n / 1e9).toFixed(2)}B` : n >= 1e6 ? `${(n / 1e6).toFixed(1)}M` : `${n}`;
  return (
    `${m.scaleName}@${m.deviceName}: designed ${b(m.designedParams)} · ` +
    `addressable ${b(m.addressableParams)} · resident ${b(m.residentParams)} · ` +
    `Q ${m.quantumStabilizerQubits}q→${b(m.quantumStabilizerDim)}dim` +
    `${m.reachesBillion ? ' · ✦1B' : ''}`
  );
}
