/**
 * Puppet-master NPCs — AETHON, SELENE, and KRONOS orbit the arena as glowing tetrahedra and
 * periodically meddle with the simulation (chaos spikes, weather shifts, mass mutations).
 * Faithful port of legacy lines 480-503; Known Bug 14 fix: mutations are counted.
 */
import * as THREE from 'three';
import { clamp } from '../math/scalar';
import { creatureDrive } from './cognition';
import { ARENA_MID, ARENA_Y, CHAOS_MAX, CHAOS_MIN, WEATHERS } from './constants';
import { POINT_LIGHT_GAIN } from './environment';
import type { PuppetEvent, SimContext } from '../types';
import type { EntityManager } from './entities';

type PuppetAction = 'chaos' | 'weather' | 'mutate';

/** Static per-puppet tuning (legacy `PMS` table). */
interface PuppetConfig {
  readonly name: string;
  readonly hue: number;
  /** Orbit radius. */
  readonly orb: number;
  /** Orbit angular speed (rad/s of sim time). */
  readonly spd: number;
  /** Base hover height. */
  readonly y: number;
  readonly act: PuppetAction;
  /** Ticks between actions (timer advances at dt*30/frame). */
  readonly iv: number;
}

// Legacy orbits × ARENA_MID, hover heights × ARENA_Y (V3.1 — the trio patrols the
// populated mid-field of the 5× arena instead of hugging the old 65u core).
const CONFIGS: readonly PuppetConfig[] = [
  {
    name: 'AETHON',
    hue: 0.08,
    orb: 45 * ARENA_MID,
    spd: 0.07,
    y: 35 * ARENA_Y,
    act: 'chaos',
    iv: 400,
  },
  {
    name: 'SELENE',
    hue: 0.6,
    orb: 55 * ARENA_MID,
    spd: -0.05,
    y: 42 * ARENA_Y,
    act: 'weather',
    iv: 600,
  },
  {
    name: 'KRONOS',
    hue: 0.3,
    orb: 50 * ARENA_MID,
    spd: 0.03,
    y: 38 * ARENA_Y,
    act: 'mutate',
    iv: 500,
  },
];

// Pre-built toast strings so action ticks never build strings inside update().
const CHAOS_MESSAGE = 'stokes the chaos';
const WEATHER_MESSAGES: readonly string[] = WEATHERS.map((w) => `shifts to ${w}`);
const RESHAPE_MESSAGES: readonly string[] = Array.from(
  { length: 31 },
  (_, n) => `reshapes ${n} organisms`,
);

// Scratch event object — reused per emit; listeners must not retain it across calls.
const EVENT: PuppetEvent = { name: '', action: '' };

/** Population targets (CONTRACTS V14 — "100 Puppeteers"). The 3 named heroes keep their roles; the
 *  rest are lesser hands generated by a deterministic golden-angle layout (NO rng draws, so the main
 *  seeded stream is untouched). Phone tier stays light. */
const PUPPET_COUNT_DESKTOP = 100;
const PUPPET_COUNT_MOBILE = 14;
/** Only the first few puppeteers carry point lights (WebGL dynamic-light cap). */
const LIT_PUPPETS = 4;
/** Golden ratio − 1 (golden-angle fraction) for an even, non-repeating lesser-puppet layout. */
const PHI = 0.618033988749895;

/** F-ECON-CREATURES V19: reference purse + boldness band — a rich puppeteer MEDDLES more often
 *  (shorter effective interval) and shows it (brighter + larger), a broke one falls quiet. Boldness
 *  is RELATIVE to the live mean puppeteer wealth so it's inflation-proof. */
const PUP_ECON_REF = 180;
const PUP_BOLD_MIN = 0.45;
const PUP_BOLD_MAX = 2.4;

/** F-COGNITION V25: a puppeteer is a SCHEMER — it perceives the disorder in its sector (entity
 *  density below its orbit) and meddles MORE where there's chaos to exploit, remembering when it last
 *  acted. Reuses the {@link creatureDrive} kernel with threat=0 (disembodied — it never flees). */
const PUP_OPP_R = 42; // opportunity sense radius (XZ) — the meddling sector
const PUP_OPP_CAP = 28; // this many entities below ⇒ max opportunity
const PUP_SAT_DECAY = 0.05; // meddle-satiation creep per second
const PUP_SAT_BUMP = 0.6; // satiation gained each time it meddles

/** Deterministic config for lesser puppeteer `i` (0-based, beyond the 3 heroes). No rng. */
function lesserConfig(i: number): PuppetConfig {
  return {
    name: `WRAITH-${i + 1}`,
    hue: (i * PHI) % 1,
    orb: (38 + (i % 8) * 6) * ARENA_MID,
    spd: (i % 2 === 0 ? 1 : -1) * (0.03 + (i % 5) * 0.012),
    y: (26 + (i % 9) * 3) * ARENA_Y,
    // Lesser hands only RESHAPE — weather/chaos from 97 of them would strobe the world.
    act: 'mutate',
    iv: 1400 + (i % 13) * 110, // long, staggered intervals so meddling is steady, not a flood
  };
}

/** Live per-puppet state. */
interface Puppet {
  readonly cfg: PuppetConfig;
  readonly mesh: THREE.Mesh;
  readonly mat: THREE.MeshStandardMaterial;
  readonly ring: THREE.Mesh;
  /** Point light — present only on the first {@link LIT_PUPPETS} (the rest glow emissive). */
  readonly light?: THREE.PointLight;
  /** Action tick accumulator (legacy `ti`). */
  ti: number;
  /** F-COGNITION V25: memory of recent meddling 0 (itching to act) .. 1 (spent). */
  satiation: number;
}

/**
 * Orchestrates the three puppet masters: orbital motion, pulsing glow, and interval-driven
 * meddling. Interventions are surfaced to the HUD via the injected `onEvent` callback
 * (legacy `showNM` toast).
 */
export class PuppetMasterSystem {
  private readonly ctx: SimContext;
  private readonly entities: EntityManager;
  private readonly onEvent: (e: PuppetEvent) => void;
  private readonly pms: Puppet[] = [];
  /** F-ECON-CREATURES V19: economic net-worth provider by puppeteer index (null ⇒ no coupling). */
  private econWealth: ((puppetIndex: number) => number) | null = null;

  /**
   * Builds the puppeteer cabal (CONTRACTS V14: 100 on desktop+, 14 on phone). The 3 named heroes
   * (AETHON/SELENE/KRONOS) keep their original roles + point lights; the rest are lesser hands laid
   * out by a deterministic golden-angle pattern (no rng), each reshaping the world on a long stagger.
   */
  constructor(ctx: SimContext, entities: EntityManager, onEvent: (e: PuppetEvent) => void) {
    this.ctx = ctx;
    this.entities = entities;
    this.onEvent = onEvent;
    const count = ctx.quality.isMobile ? PUPPET_COUNT_MOBILE : PUPPET_COUNT_DESKTOP;
    for (let i = 0; i < count; i++) {
      const cfg = i < CONFIGS.length ? CONFIGS[i]! : lesserConfig(i - CONFIGS.length);
      this.addPuppet(cfg, i < LIT_PUPPETS);
    }
  }

  /**
   * F-ECON-CREATURES V19: wire in the AURUM/UMBRA economy so each puppeteer's WEALTH drives how often
   * it meddles — a rich hand reshapes/stokes the world more frequently (and glows brighter + larger),
   * a broke one falls quiet. `wealthByIndex(i)` returns puppeteer i's AURUM net worth. Null (default +
   * tests) leaves the legacy cadence untouched, so the puppet-master goldens stay byte-identical.
   */
  attachEconomy(wealthByIndex: ((puppetIndex: number) => number) | null): void {
    this.econWealth = wealthByIndex;
  }

  /** Build one puppeteer (tetra core + torus ring; a point light only on the first LIT_PUPPETS). */
  private addPuppet(cfg: PuppetConfig, lit: boolean): void {
    const ctx = this.ctx;
    const mat = new THREE.MeshStandardMaterial({
      color: new THREE.Color().setHSL(cfg.hue, 0.8, 0.3),
      emissive: new THREE.Color().setHSL(cfg.hue, 0.9, 0.15),
      emissiveIntensity: 2,
      transparent: true,
      opacity: 0.6,
      side: THREE.DoubleSide,
    });
    const mesh = new THREE.Mesh(new THREE.TetrahedronGeometry(1.5, 1), mat);
    const ring = new THREE.Mesh(
      new THREE.TorusGeometry(2.5, 0.08, 6, 32),
      new THREE.MeshBasicMaterial({
        color: new THREE.Color().setHSL(cfg.hue, 0.9, 0.5),
        transparent: true,
        opacity: 0.3,
      }),
    );
    ring.rotation.x = Math.PI / 2;
    mesh.add(ring);
    let light: THREE.PointLight | undefined;
    if (lit) {
      light = new THREE.PointLight(
        new THREE.Color().setHSL(cfg.hue, 0.9, 0.5),
        3 * POINT_LIGHT_GAIN,
        25,
        0, // legacy r128 falloff model — see LEGACY_LIGHT_GAIN in environment.ts
      );
      mesh.add(light);
    }
    ctx.scene.add(mesh);
    this.pms.push({ cfg, mesh, mat, ring, light, ti: 0, satiation: 0.5 });
  }

  /** Number of puppet masters (constant 3 — feeds the telemetry `puppeteers` field). */
  get count(): number {
    return this.pms.length;
  }

  /**
   * Orbit, pulse, and fire interval actions (legacy 492-503).
   * O(1) per frame (3 puppets); action ticks are O(1) except 'mutate' which is O(30).
   * Allocation-free: precomputed messages + module scratch event object.
   */
  update(dt: number, t: number): void {
    // F-ECON-CREATURES V19: centre boldness on the LIVE mean puppeteer wealth (relative,
    // inflation-proof) so the rich meddle more + glow brighter, the broke fall quiet.
    let meanWorth = PUP_ECON_REF;
    if (this.econWealth) {
      let sw = 0;
      const nn = this.pms.length;
      for (let k = 0; k < nn; k++) sw += this.econWealth(k);
      meanWorth = Math.max(1, sw / Math.max(1, nn));
    }
    for (let i = 0; i < this.pms.length; i++) {
      const pm = this.pms[i];
      if (!pm) continue; // noUncheckedIndexedAccess: i < length
      const cfg = pm.cfg;
      let boldness = 1;
      if (this.econWealth)
        boldness = clamp(this.econWealth(i) / meanWorth, PUP_BOLD_MIN, PUP_BOLD_MAX);
      const ang = t * cfg.spd;
      pm.mesh.position.set(
        Math.cos(ang) * cfg.orb,
        cfg.y + Math.sin(t * 0.3 + cfg.hue * 10) * 5,
        Math.sin(ang) * cfg.orb,
      );
      // F-COGNITION V25: PERCEIVE the disorder in this hand's sector (entity density below) + REMEMBER
      // recent meddling → a scheming opportunism. threat=0 (disembodied; never flees); the HUNT drive
      // is the meddle urge, AGITATION the restless glow/spin. Reuses the shared creatureDrive kernel.
      const here = pm.mesh.position;
      const opportunity = clamp(
        this.ctx.grid.query(here.x, here.z, PUP_OPP_R).length / PUP_OPP_CAP,
        0,
        1,
      );
      pm.satiation = clamp(pm.satiation - PUP_SAT_DECAY * dt, 0, 1);
      const drive = creatureDrive({
        threat: 0,
        prey: opportunity,
        satiation: pm.satiation,
        boldness,
      });
      pm.mesh.rotation.x += dt * 0.5;
      pm.mesh.rotation.y += dt * (0.7 + drive.agitation * 0.5); // restless when there's chaos to exploit
      // Wealth shows on the body: a rich hand looms larger (the visible purse).
      pm.mesh.scale.setScalar(0.8 + 0.25 * boldness);
      pm.ring.rotation.z = t * 2;
      if (pm.light)
        pm.light.intensity =
          (2 + Math.sin(t * 3 + cfg.hue * 20) * 1.5) * POINT_LIGHT_GAIN * (0.7 + 0.35 * boldness);
      pm.mat.emissiveIntensity =
        (1.5 + Math.sin(t * 2 + cfg.hue * 15) * 0.8) *
        (0.65 + 0.4 * boldness) *
        (0.8 + 0.4 * drive.agitation);
      pm.ti += dt * 30;
      // Meddle cadence: WEALTH (V19 boldness) × the V25 opportunism HUNT drive — a rich hand over a
      // disordered, target-rich sector that hasn't acted lately strikes soonest; a spent one waits.
      if (pm.ti >= cfg.iv / (boldness * (0.6 + 0.5 * drive.hunt))) {
        pm.ti = 0;
        pm.satiation = clamp(pm.satiation + PUP_SAT_BUMP, 0, 1); // remember the meddle
        this.act(cfg);
      }
    }
  }

  /** Perform one interval action (legacy 498-501). */
  private act(cfg: PuppetConfig): void {
    const ctx = this.ctx;
    const rng = ctx.rng;
    switch (cfg.act) {
      case 'chaos': {
        ctx.state.chaos = clamp(ctx.state.chaos + 0.5 + rng() * 2, CHAOS_MIN, CHAOS_MAX * 0.7);
        this.emit(cfg.name, CHAOS_MESSAGE);
        ctx.sfx('warp');
        break;
      }
      case 'weather': {
        ctx.state.weatherIdx = Math.floor(rng() * WEATHERS.length);
        // Invariant: weatherIdx ∈ [0, WEATHERS.length) and WEATHER_MESSAGES maps 1:1 to WEATHERS.
        this.emit(cfg.name, WEATHER_MESSAGES[ctx.state.weatherIdx]!);
        ctx.sfx('crystallize');
        break;
      }
      case 'mutate': {
        const list = this.entities.list;
        const mc = Math.min(30, list.length);
        for (let mi = 0; mi < mc; mi++) {
          const target = list[Math.floor(rng() * list.length)];
          // Remorph rolls over the LIVE morph table (250 in phylum mode).
          if (target) this.entities.remorph(target, Math.floor(rng() * ctx.morphs.length));
        }
        // Known Bug 14: the counter is now read by telemetry (#v8), so keep it accurate.
        ctx.state.mutations += mc;
        // Invariant: mc ∈ [0, 30] and RESHAPE_MESSAGES has 31 entries.
        this.emit(cfg.name, RESHAPE_MESSAGES[mc]!);
        ctx.sfx('mutate');
        break;
      }
    }
  }

  /** Fill the scratch event and notify the HUD listener. O(1), allocation-free. */
  private emit(name: string, action: string): void {
    EVENT.name = name;
    EVENT.action = action;
    this.onEvent(EVENT);
  }
}
